name: PokeRougeUtil Build

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pip install pytest
          PYTHONPATH=$(pwd) pytest

  deploy-render:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Push to Render branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout main
          git pull origin main

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/moffd234/PokeRouge-Util-API.git

          git checkout -B render
          git push origin render --force

  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: postman collection run "34748211-42f438b0-e880-49c7-8c9d-429b5e021289" \
          -e "Postman/pokerouge-env.json"